#!/usr/bin/env python3
"""Round 5 · Lane A2 — formula REGION detection.

The order says: detect the formula region on the PAGE, and if it cannot be extracted safely,
withhold the region but keep its crop. That only works if a region is found even when the OCR lost
its digits — a region the detector never saw cannot be withheld, it is simply missing, and the
child is shown whatever prose fragment survived. So the unit under test here is «did we find the
printed structure», separately from «could we read it».

Every picture below is a real shape from the Toán books, drawn small enough to read:
a stacked fraction, a plus, a minus, an equals sign, a division sign, and an underline.
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'corpus'))

from mathfix import detect as D              # noqa: E402
from mathfix.inkmask import InkMask          # noqa: E402
from mathfix.tokens import Token             # noqa: E402


def mask(art):
    return InkMask.from_ascii(art)


# «1 over 5»: numerator, a detached bar, denominator.
FRACTION = """\
....................
.........#..........
........##..........
.........#..........
.........#..........
....................
....###########.....
....................
........####........
.......#............
.......####.........
..........#.........
.......###..........
....................
"""

# «+»: the same bar, but the ink above and below is the SAME stroke, attached to it.
PLUS = """\
....................
....................
.........#..........
.........#..........
.........#..........
.........#..........
....###########.....
.........#..........
.........#..........
.........#..........
.........#..........
....................
....................
....................
"""

# «=»: two bars, each of which has a bar above or below it.
EQUALS = """\
....................
....................
....................
....................
....###########.....
....................
....................
....###########.....
....................
....................
....................
....................
....................
....................
"""

# «−» standing alone between two numbers on the same baseline: nothing above, nothing below.
MINUS = """\
....................
....................
....................
....................
....................
....................
....###########.....
....................
....................
....................
....................
....................
....................
....................
"""

# A heading with a rule under it: ink above, nothing below.
UNDERLINE = """\
....................
....................
....#..#..#..#......
....#..#..#..#......
....#..#..#..#......
....................
....###########.....
....................
....................
....................
....................
....................
....................
....................
"""

PARAMS = dict(min_len_frac=0.30, max_len_frac=0.90, max_thick_frac=0.20)


class TestFractionRegionShape(unittest.TestCase):
    def regions(self, art, tokens=()):
        return D.find_fraction_regions(mask(art), list(tokens), bar_params=PARAMS)

    def test_a_stacked_fraction_is_a_region(self):
        r = self.regions(FRACTION)
        self.assertEqual(len(r), 1)
        self.assertEqual(r[0].kind, 'bar_region_unreadable')   # no OCR tokens were supplied
        self.assertTrue(r[0].ink_above)
        self.assertTrue(r[0].ink_below)

    def test_a_plus_sign_is_not_a_fraction_because_its_ink_touches_the_bar(self):
        self.assertEqual(self.regions(PLUS), [])

    def test_an_equals_sign_is_not_a_fraction_because_the_ink_above_is_another_bar(self):
        self.assertEqual(self.regions(EQUALS), [])

    def test_a_lone_minus_is_not_a_fraction(self):
        self.assertEqual(self.regions(MINUS), [])

    def test_an_underline_is_not_a_fraction_because_nothing_sits_below_it(self):
        self.assertEqual(self.regions(UNDERLINE), [])


class TestTokenAttachment(unittest.TestCase):
    """The bar comes from the page; the digits come from the OCR — and only when unambiguous."""

    def bar_tokens(self, num=None, den=None):
        # The FRACTION picture is 20 × 14; the bar is at rows 6..7, columns 4..15.
        out = []
        if num is not None:
            out.append(Token(num, x=8 / 20, y=1 / 14, w=2 / 20, h=4 / 14, conf=1.0, index=0))
        if den is not None:
            out.append(Token(den, x=7 / 20, y=8 / 14, w=4 / 20, h=5 / 14, conf=1.0, index=1))
        return out

    def test_both_halves_present_gives_an_extractable_stacked_fraction(self):
        r = D.find_fraction_regions(mask(FRACTION), self.bar_tokens('1', '5'), bar_params=PARAMS)
        self.assertEqual(len(r), 1)
        self.assertEqual(r[0].kind, 'stacked_fraction')
        self.assertTrue(r[0].extractable)
        self.assertEqual((r[0].numerator.stripped, r[0].denominator.stripped), ('1', '5'))

    def test_a_missing_denominator_token_is_a_detected_but_unextractable_region(self):
        """The real «c) 3 − 11/8» of Toán 5 tập một p23: the OCR read «11» and lost the «8»."""
        r = D.find_fraction_regions(mask(FRACTION), self.bar_tokens('11', None), bar_params=PARAMS)
        self.assertEqual(len(r), 1)
        self.assertEqual(r[0].kind, 'stacked_fraction')
        self.assertFalse(r[0].extractable)
        self.assertEqual(r[0].reason, 'denominator_token_missing')

    def test_a_non_digit_token_is_never_read_as_a_fraction_half(self):
        r = D.find_fraction_regions(mask(FRACTION), self.bar_tokens('a) 7 +', '5'), bar_params=PARAMS)
        self.assertFalse(r[0].extractable)
        self.assertEqual(r[0].reason, 'numerator_token_missing')

    def test_two_candidate_numerators_fail_closed(self):
        toks = self.bar_tokens('1', '5')
        toks.append(Token('3', x=11 / 20, y=1 / 14, w=2 / 20, h=4 / 14, conf=1.0, index=2))
        r = D.find_fraction_regions(mask(FRACTION), toks, bar_params=PARAMS)
        self.assertFalse(r[0].extractable)
        self.assertEqual(r[0].reason, 'numerator_ambiguous')

    def test_a_token_shared_by_two_regions_fails_both_closed(self):
        """One digit cannot be the denominator of one fraction and the numerator of another."""
        art = FRACTION + FRACTION.split('\n', 1)[1]
        m = mask(art)
        h = m.height
        shared = Token('5', x=7 / 20, y=8 / h, w=4 / 20, h=5 / h, conf=1.0, index=1)
        top = Token('1', x=8 / 20, y=1 / h, w=2 / 20, h=4 / h, conf=1.0, index=0)
        bottom = Token('9', x=7 / 20, y=(8 + 13) / h, w=4 / 20, h=5 / h, conf=1.0, index=2)
        r = D.find_fraction_regions(m, [top, shared, bottom], bar_params=PARAMS)
        self.assertEqual(len(r), 2)
        self.assertTrue(all(not x.extractable for x in r), [x.reason for x in r])
        self.assertIn('token_shared', [x.reason for x in r])


class TestLineRegionCensus(unittest.TestCase):
    """The other region kinds the order names — reported, never repaired by this lane."""

    def test_an_inline_expression_inside_prose(self):
        t = [Token('Ta có 7 + 1 = 8 nên phép tính đúng.', 0.1, 0.2, 0.5, 0.02, 1.0, 0)]
        self.assertEqual(D.classify_token(t[0]), 'inline_expression')

    def test_a_bare_number_is_a_numeric_answer(self):
        self.assertEqual(D.classify_token(Token('1 360', 0.1, 0.2, 0.05, 0.02, 1.0, 0)), 'numeric_answer')

    def test_a_short_operator_run_is_a_display_formula_fragment(self):
        self.assertEqual(D.classify_token(Token('a) 7 +', 0.1, 0.2, 0.07, 0.02, 1.0, 0)),
                         'display_formula_fragment')

    def test_plain_prose_is_not_a_formula_region(self):
        self.assertIsNone(D.classify_token(Token('Để chia đều bánh cho các bạn.', 0.1, 0.2, 0.5, 0.02, 1.0, 0)))


if __name__ == '__main__':
    unittest.main()
